# Generated by Django 2.2.3 on 2019-09-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abc',
            new_name='abcModel',
        ),
    ]
