# Generated by Django 2.2.3 on 2019-09-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190914_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abcModel',
            new_name='QuoteModel',
        ),
    ]
